### ISSUE TITLE
ImportError: No module named corerv

### ISSUE THREAD

**Issue by ezhilrean** [waldirio/rvtools_python#33]
Hi Team,
I could not able to use the rvtools on Linux machine. I am getting the below error. 

# rvtools --help
Traceback (most recent call last):
  File "/bin/rvtools", line 7, in <module>
    from rvtools import rvtools
  File "/usr/lib/python2.7/site-packages/rvtools/rvtools.py", line 11, in <module>
    from rvtools.corerv import *
ImportError: No module named corerv

 **I have followed the below procedures.** 

I am using below system configurations.

#  cat /etc/redhat-release
CentOS Linux release 7.7.1908 (Core)

# python --version
Python 2.7.5

And also I have installed some perquisites python packages on my machine.
pip install pyrvtools
pip install pyVim
pip install pyvmomi

**Comment by waldirio** [comment]
Hello @ezhilrean, thanks for your contact.

As you can see on the main page, this code was written/tested on python 3.6+
```
Ps.: Necessary python 3.6 or greather. Improving the code to be supported by 2.7 as well
```
Please, install python3.6 or gt and everything will work as expected.

Please, let me know if you have additional questions or concerns.

Waldirio

**Comment by ezhilrean** [comment]
Thanks @waldirio ,

I have installed requirements.txt  using the command pip install -r requirements.txt", then it is working good. thanks for support

**Comment by waldirio** [comment]
Hello @ezhilrean 

Sure thing. Glad to help and sorry for my delay here.
Waldirio
